// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"工作台","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"基础数据","path":"/base","icon":"DatabaseOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"货品资料","path":"/base/goods","parentId":"3","id":"4"},"5":{"name":"门店资料","path":"/base/store","parentId":"3","id":"5"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__base__Goods__index" */'@/pages/base/Goods/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__base__Store__index" */'@/pages/base/Store/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'D:/wook/project/GoodsFlow/code/goodsFlow-admin/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
