// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from 'D:/wook/project/GoodsFlow/code/goodsFlow-admin/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import DatabaseOutlined from 'D:/wook/project/GoodsFlow/code/goodsFlow-admin/node_modules/@ant-design/icons/es/icons/DatabaseOutlined';
export default { DashboardOutlined, DatabaseOutlined };
